# Generated by Django 5.0.1 on 2026-01-11 21:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScraperRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "En ejecución"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                            ("PARTIAL", "Parcial"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("API", "API")],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="inicio",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="fin"),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="duración"
                    ),
                ),
                (
                    "products_scraped",
                    models.PositiveIntegerField(default=0, verbose_name="scrapeados"),
                ),
                (
                    "products_updated",
                    models.PositiveIntegerField(default=0, verbose_name="actualizados"),
                ),
                (
                    "products_created",
                    models.PositiveIntegerField(default=0, verbose_name="creados"),
                ),
                (
                    "errors_count",
                    models.PositiveIntegerField(default=0, verbose_name="errores"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraper_runs",
                        to="products.store",
                        verbose_name="tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "ejecución",
                "verbose_name_plural": "ejecuciones",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ScraperError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("CONNECTION", "Conexión"),
                            ("TIMEOUT", "Timeout"),
                            ("PARSE", "Parseo"),
                            ("VALIDATION", "Validación"),
                            ("NOT_FOUND", "No encontrado"),
                            ("OTHER", "Otro"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("error_message", models.TextField(verbose_name="mensaje")),
                ("stack_trace", models.TextField(blank=True, verbose_name="stack")),
                (
                    "url",
                    models.URLField(blank=True, max_length=1000, verbose_name="URL"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="fecha",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="resuelto"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraper_errors",
                        to="products.productlisting",
                        verbose_name="listing",
                    ),
                ),
                (
                    "scraper_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="scrapers.scraperrun",
                        verbose_name="ejecución",
                    ),
                ),
            ],
            options={
                "verbose_name": "error",
                "verbose_name_plural": "errores",
                "ordering": ["-occurred_at"],
            },
        ),
    ]
