# Generated by Django 5.0.1 on 2026-01-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="scrapererror",
            table="scraper_error",
        ),
        migrations.AlterModelTable(
            name="scraperrun",
            table="scraper_run",
        ),
    ]
