# Generated by Django 5.0.1 on 2026-01-12 00:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_alter_category_description_alter_category_is_active_and_more",
        ),
        ("scrapers", "0002_alter_scrapererror_table_alter_scraperrun_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapererror",
            name="resolution_notes",
            field=models.TextField(
                blank=True,
                help_text="Notas sobre cómo se resolvió el error",
                verbose_name="notas de resolución",
            ),
        ),
        migrations.AddField(
            model_name="scraperrun",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="ID de la tarea de Celery",
                max_length=255,
                verbose_name="ID tarea",
            ),
        ),
        migrations.AlterField(
            model_name="scrapererror",
            name="error_message",
            field=models.TextField(
                help_text="Mensaje descriptivo del error", verbose_name="mensaje"
            ),
        ),
        migrations.AlterField(
            model_name="scrapererror",
            name="error_type",
            field=models.CharField(
                choices=[
                    ("CONNECTION", "Conexión"),
                    ("TIMEOUT", "Timeout"),
                    ("PARSE", "Parseo"),
                    ("VALIDATION", "Validación"),
                    ("NOT_FOUND", "No encontrado"),
                    ("OTHER", "Otro"),
                ],
                db_index=True,
                default="OTHER",
                help_text="Tipo de error ocurrido",
                max_length=20,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="scrapererror",
            name="is_resolved",
            field=models.BooleanField(
                default=False,
                help_text="Si el error ya fue resuelto",
                verbose_name="resuelto",
            ),
        ),
        migrations.AlterField(
            model_name="scrapererror",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                help_text="ProductListing relacionado",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scraper_errors",
                to="products.productlisting",
                verbose_name="listing",
            ),
        ),
        migrations.AlterField(
            model_name="scrapererror",
            name="occurred_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Momento en que ocurrió el error",
                verbose_name="fecha",
            ),
        ),
        migrations.AlterField(
            model_name="scrapererror",
            name="scraper_run",
            field=models.ForeignKey(
                help_text="Ejecución en la que ocurrió el error",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="errors",
                to="scrapers.scraperrun",
                verbose_name="ejecución",
            ),
        ),
        migrations.AlterField(
            model_name="scrapererror",
            name="stack_trace",
            field=models.TextField(
                blank=True,
                help_text="Stack trace completo del error",
                verbose_name="stack",
            ),
        ),
        migrations.AlterField(
            model_name="scrapererror",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="URL donde ocurrió el error",
                max_length=1000,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="errors_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número de errores encontrados",
                verbose_name="errores",
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="execution_time",
            field=models.DurationField(
                blank=True,
                help_text="Duración total de la ejecución",
                null=True,
                verbose_name="duración",
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="finished_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento de finalización",
                null=True,
                verbose_name="fin",
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Notas adicionales sobre la ejecución",
                verbose_name="notas",
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="products_created",
            field=models.PositiveIntegerField(
                default=0, help_text="Productos nuevos creados", verbose_name="creados"
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="products_scraped",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total de productos procesados",
                verbose_name="scrapeados",
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="products_updated",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Productos actualizados",
                verbose_name="actualizados",
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="started_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Momento de inicio de la ejecución",
                verbose_name="inicio",
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("RUNNING", "En ejecución"),
                    ("COMPLETED", "Completado"),
                    ("FAILED", "Fallido"),
                    ("PARTIAL", "Parcial"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Estado actual de la ejecución",
                max_length=20,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="store",
            field=models.ForeignKey(
                help_text="Tienda que fue scrapeada",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraper_runs",
                to="products.store",
                verbose_name="tienda",
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("SCHEDULED", "Programado"),
                    ("API", "API"),
                ],
                default="MANUAL",
                help_text="Cómo se inició el scraping",
                max_length=20,
                verbose_name="tipo",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapererror",
            index=models.Index(
                fields=["scraper_run", "-occurred_at"],
                name="scraper_err_scraper_5381eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapererror",
            index=models.Index(
                fields=["error_type", "is_resolved"],
                name="scraper_err_error_t_25290f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapererror",
            index=models.Index(
                fields=["is_resolved", "-occurred_at"],
                name="scraper_err_is_reso_a9ac75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scraperrun",
            index=models.Index(
                fields=["store", "-started_at"], name="scraper_run_store_i_fddf9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scraperrun",
            index=models.Index(
                fields=["status", "-started_at"], name="scraper_run_status_6d3f9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scraperrun",
            index=models.Index(
                fields=["trigger_type"], name="scraper_run_trigger_407f10_idx"
            ),
        ),
    ]
