# Generated by Django 5.0.1 on 2026-01-11 21:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ML", "MercadoLibre"),
                            ("EX", "Éxito"),
                            ("FA", "Falabella"),
                            ("AL", "Alkosto"),
                            ("JU", "Jumbo"),
                        ],
                        max_length=2,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("base_url", models.URLField(verbose_name="URL base")),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "scraping_enabled",
                    models.BooleanField(
                        default=True, verbose_name="scraping habilitado"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
            ],
            options={
                "verbose_name": "tienda",
                "verbose_name_plural": "tiendas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["name"],
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="nombre")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="marca"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=200, verbose_name="modelo"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "main_image_url",
                    models.URLField(blank=True, max_length=1000, verbose_name="imagen"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                        verbose_name="categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_sku", models.CharField(max_length=200, verbose_name="SKU")),
                ("url", models.URLField(max_length=1000, verbose_name="URL")),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=1000, verbose_name="imagen"),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="precio",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="precio original",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="disponible"),
                ),
                (
                    "stock_status",
                    models.CharField(blank=True, max_length=100, verbose_name="stock"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "last_scraped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último scraping"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="products.product",
                        verbose_name="producto",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="products.store",
                        verbose_name="tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "listado",
                "verbose_name_plural": "listados",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="precio",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="precio original",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="disponible"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="fecha",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.productlisting",
                        verbose_name="listado",
                    ),
                ),
            ],
            options={
                "verbose_name": "precio",
                "verbose_name_plural": "precios",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_pr_name_9ff0a3_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="products_pr_brand_4bfaa4_idx"),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["listing", "-recorded_at"],
                name="products_pr_listing_ecf904_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["product", "store"], name="products_pr_product_88a293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["current_price"], name="products_pr_current_8504dc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productlisting",
            unique_together={("store", "store_sku")},
        ),
    ]
