# Generated by Django 5.0.1 on 2026-01-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productlisting",
            name="products_pr_current_8504dc_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="main_image_url",
        ),
        migrations.RemoveField(
            model_name="productlisting",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="productlisting",
            name="original_price",
        ),
    ]
