# Generated by Django 5.0.1 on 2026-01-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_remove_productlisting_products_pr_current_8504dc_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="price",
            new_name="price_listing_7fe6f8_idx",
            old_name="products_pr_listing_ecf904_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="product_name_c4c985_idx",
            old_name="products_pr_name_9ff0a3_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="product_brand_a7389b_idx",
            old_name="products_pr_brand_4bfaa4_idx",
        ),
        migrations.RenameIndex(
            model_name="productlisting",
            new_name="product_lis_product_33760d_idx",
            old_name="products_pr_product_88a293_idx",
        ),
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="price",
            table="price",
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
        migrations.AlterModelTable(
            name="productlisting",
            table="product_listing",
        ),
        migrations.AlterModelTable(
            name="store",
            table="store",
        ),
    ]
