# Generated by Django 5.0.1 on 2026-01-11 22:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_rename_products_pr_listing_ecf904_idx_price_listing_7fe6f8_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descripción de la categoría",
                verbose_name="descripción",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica si la categoría está activa",
                verbose_name="activa",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Nombre de la categoría",
                max_length=200,
                verbose_name="nombre",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría padre (None para categorías raíz)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
                verbose_name="padre",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Slug para URLs (generado automáticamente)",
                max_length=220,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Si el producto estaba disponible al momento del registro",
                verbose_name="disponible",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="listing",
            field=models.ForeignKey(
                help_text="ProductListing al que pertenece",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="products.productlisting",
                verbose_name="listado",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio original antes de descuento",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="precio original",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio actual del producto",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="precio",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="recorded_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Fecha y hora del registro de precio",
                verbose_name="fecha",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text="Marca del producto",
                max_length=100,
                verbose_name="marca",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría del producto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descripción detallada del producto",
                verbose_name="descripción",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el producto está activo",
                verbose_name="activo",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(
                blank=True,
                help_text="Modelo específico del producto",
                max_length=200,
                verbose_name="modelo",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Nombre completo del producto",
                max_length=500,
                verbose_name="nombre",
            ),
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL de la imagen del producto",
                max_length=1000,
                verbose_name="imagen",
            ),
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el listing está activo",
                verbose_name="activo",
            ),
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Disponibilidad actual",
                verbose_name="disponible",
            ),
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="last_scraped_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Última vez que se hizo scraping",
                null=True,
                verbose_name="último scraping",
            ),
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="product",
            field=models.ForeignKey(
                help_text="Producto al que pertenece",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="products.product",
                verbose_name="producto",
            ),
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="stock_status",
            field=models.CharField(
                blank=True,
                help_text='Estado del stock (ej: "En stock", "Últimas unidades")',
                max_length=100,
                verbose_name="stock",
            ),
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="store",
            field=models.ForeignKey(
                help_text="Tienda donde se vende",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="products.store",
                verbose_name="tienda",
            ),
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="store_sku",
            field=models.CharField(
                help_text="SKU o código en la tienda",
                max_length=200,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="url",
            field=models.URLField(
                help_text="URL del producto en la tienda",
                max_length=1000,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="base_url",
            field=models.URLField(
                help_text="URL base del sitio web", verbose_name="URL base"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="code",
            field=models.CharField(
                choices=[
                    ("ML", "MercadoLibre"),
                    ("EX", "Éxito"),
                    ("FA", "Falabella"),
                    ("AL", "Alkosto"),
                    ("JU", "Jumbo"),
                ],
                help_text="Código único de 2 caracteres",
                max_length=2,
                unique=True,
                verbose_name="código",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica si la tienda está activa",
                verbose_name="activa",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(
                help_text="Nombre completo de la tienda",
                max_length=100,
                unique=True,
                verbose_name="nombre",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="scraping_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Habilitar scraping automático",
                verbose_name="scraping habilitado",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="category_slug_4e15ec_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent"], name="category_parent__869b08_idx"),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["is_available"], name="price_is_avai_a8634f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["-recorded_at"], name="price_recorde_f85836_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="product_categor_71bada_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["is_active", "is_available"],
                name="product_lis_is_acti_37f94b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["last_scraped_at"], name="product_lis_last_sc_e7fe62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["code"], name="store_code_91ed9d_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["is_active", "scraping_enabled"],
                name="store_is_acti_d48f10_idx",
            ),
        ),
    ]
