# Generated by Django 5.0.1 on 2026-01-12 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_alter_category_description_alter_category_is_active_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="category_slug_4e15ec_idx",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.AlterUniqueTogether(
            name="productlisting",
            unique_together={("store",)},
        ),
        migrations.RemoveField(
            model_name="productlisting",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="productlisting",
            name="store_sku",
        ),
    ]
