# Generated by Django 5.0.1 on 2026-01-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_category_category_slug_4e15ec_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="URL de la categoría en la tienda",
                max_length=1000,
                verbose_name="URL",
            ),
        ),
    ]
