# Generated by Django 5.0.1 on 2026-01-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_category_url"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="category_parent__869b08_idx",
        ),
        migrations.RemoveIndex(
            model_name="price",
            name="price_recorde_f85836_idx",
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="category",
            name="store",
            field=models.ForeignKey(
                default=1,
                help_text="Tienda a la que pertenece esta categoría",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="products.store",
                verbose_name="tienda",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría padre dentro de la misma tienda",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
                verbose_name="padre",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("store", "name", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="productlisting",
            unique_together={("product", "store")},
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["store", "parent"], name="category_store_i_8a4d88_idx"
            ),
        ),
    ]
