# Generated by Django 5.0.1 on 2026-01-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_category_category_parent__869b08_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="price",
            name="price_listing_7fe6f8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productlisting",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["store", "is_active"], name="category_store_i_f58efd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["listing", "recorded_at"], name="price_listing_d57f0a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("store", "parent", "name"), name="uq_category_store_parent_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                check=models.Q(("name", ""), _negated=True),
                name="category_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("original_price__isnull", True),
                    ("original_price__gte", models.F("price")),
                    _connector="OR",
                ),
                name="price_original_gte_price_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("name", ""), _negated=True),
                name="product_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="productlisting",
            constraint=models.UniqueConstraint(
                fields=("product", "store"), name="uq_listing_product_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.CheckConstraint(
                check=models.Q(("name", ""), _negated=True), name="store_name_not_blank"
            ),
        ),
    ]
